name: Build on PR

on:
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    name : Build the project
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Nods.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
        
      - name: Install dependencies
        run: npm install

      # -name : Run prisma client
      #   run: cd packages/db && npx prisma generate && cd ../..

      - name: Build
        run: npm run build
  